# Generated by Django 4.1 on 2022-08-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_order_alter_product_size_shippingcustomeraddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='customer',
        ),
    ]
